feat: TypeScript conversion base
apify/apify-storage-local-js pull request #15
Opened 2021-03-19 10:20 UTC by vladfrangu

This PR sets the base for converting to TypeScript. As it stands, it allows the current project to be built as is, while also generating some form of typings (thanks tsc).

I've also made jest TS ready, and added mjs support! After this PR is merged, I can start converting files :3

2021-03-19 10:43 UTC, B4nan requested changes
looking good! left few minor notes and questions

2021-03-19 10:43 UTC, B4nan commented on tsconfig.base.json
> +	"extends": "@sapphire/ts-config"
i'd rather not extend 3rd party configs, this just hides the configuration

2021-03-19 10:43 UTC, B4nan commented on package.json
> +        "better-sqlite3-with-prebuilds": "^7.1.4",
keep this pinned to 7.1.1 for now

2021-03-19 10:43 UTC, B4nan commented on package.json
> +        "build": "tsc -b src",
can you share a bit about the `-b` flag and why is it used? never used that myself, and from the docs it feels like its doing the same as `compilerOptions.incremental`

2021-03-19 10:51 UTC, vladfrangu commented on tsconfig.base.json
> +	"extends": "@sapphire/ts-config"
If there will be a module in apify, like the eslint one, then we could move to it (and we should, as it keeps consistency). I can make it all in one file for now, if that's more feasible!

2021-03-19 10:52 UTC, vladfrangu commented on package.json
> +        "better-sqlite3-with-prebuilds": "^7.1.4",
Handled in https://github.com/apify/apify-storage-local-js/pull/15/commits/bbe067c2e603541c7a39344c958c37b699ef466a

2021-03-19 10:54 UTC, vladfrangu commented on package.json
> +        "build": "tsc -b src",
As you saw, in `src` there's also a `tsconfig.json` file. The whole structure is done in such a way that we won't have `dist/src/index.js`, but rather `dist/index.js` (as an example). Per the docs, `Builds this project and all of its dependencies specified by Project References.`

2021-03-19 10:58 UTC, B4nan commented on package.json
> +        "build": "tsc -b src",
yeah that is how i build my projects too, and never needed `-b` flag, so that is why i am asking what is that for :]

using just `-p` usually (as i have separate `tsconfig.build.json` file there)

2021-03-19 11:00 UTC, B4nan commented on tsconfig.base.json
> +	"extends": "@sapphire/ts-config"
yeah sure we could/should have a shared config for our projects, but that is a different story - i am asking for not using a 3rd party one, let's move the configuratio here directly, so it can be reviewed without searching what that preset does.

2021-03-19 11:06 UTC, vladfrangu commented on tsconfig.base.json
> +	"extends": "@sapphire/ts-config"
Done in https://github.com/apify/apify-storage-local-js/pull/15/commits/5b7a4856ff66a9d09e3a6bb3ca62167199d3c8a2

2021-03-19 11:07 UTC, vladfrangu commented on package.json
> +        "build": "tsc -b src",
Huh, interesting.. I'll have to check why we do it with `-b` in our projects, but I can move it to `-p` as you said!

2021-03-19 11:15 UTC, B4nan commented on package.json
> +        "build": "tsc -b src",
let's keep it 👍 just wanted to understand the why

2021-03-19 11:16 UTC, B4nan approved these changes

2021-03-19 18:08 UTC, pocesar commented on package.json
> +        "postbuild": "gen-esm-wrapper dist/index.js dist/index.mjs",
this doesn't seem to be needed

2021-03-19 18:08 UTC, pocesar commented on package.json
> +        "gen-esm-wrapper": "^1.1.1",
this is a small package that doesn't seem to bring a lot as a dependency (related to the postbuild phase)

2021-03-19 18:10 UTC, pocesar requested changes
`gen-esm-wrapper` can go

2021-03-19 18:10 UTC, B4nan commented on package.json
> +        "gen-esm-wrapper": "^1.1.1",
this will allow using native ESM, which is nice. why should we care about dev deps?

2021-03-19 18:11 UTC, B4nan commented
i am voting to keep it ¯\_(ツ)_/¯

2021-03-19 18:38 UTC, vladfrangu commented
> `gen-esm-wrapper` can go

While I understand, `gen-esm-wrapper` is the simplest way to automatically add native support for ESM/MJS, which I know more and more people are using. If the consensus is to remove it, then I will, just let me know 😄

2021-03-19 20:07 UTC, pocesar approved these changes
not going to be nitpicky here 😄

2021-03-21 12:41 UTC, mnmkng commented
Cool. Thanks @vladfrangu

2021-03-21 12:41 UTC, merged